# Config format schema number
format_version: 4

###################
## Model options
model_params:
  grid_size:
    - 480
    - 360
    - 32

  fea_dim: 9
  ppmodel_init_dim: 32
  use_norm: True
  dropout: 0.5  # 0.2
  circular_padding: True
  pixelShuffle: True



###################
## Data_loader options
data_loader:
  data_path: "/home/cooper/data-ssd/data5/cqy/custom_dataset/32line_remove_nan/"
  return_ref: True  # reflectivity(intensity)
  residual: 8  # residual 1-8, 0 for none
  residual_path:  "/home/cooper/data-ssd/data5/cqy/custom_dataset/32line_remove_nan/bev_res_image/autocity-polar-480-360-60.0-0.0" # "/home/cooper/data-ssd/data3/cxm/bevdata_pose_align_resolution" # "/data-ssd/data5/cxm/ljx/MotionBEV/residual-polar-sequential-480-360/"
  batch_size: 2
  shuffle: True
  drop_few_static_frames: False # False # True  # drop_few_static_frames for training, speed up training while slightly reduce the accuracy
  num_workers: 4  # Set to four times the number of available GPUs

  ignore_label: 255
  fixed_volume_space: True
  

  rotate_aug: True
  flip_aug: True
  transform_aug: True



###################
## Train params
train_params:
  name: "MotionBEVpp"
  model_load_path: "" # none for training from scratch
  check_times: 3 # 在一个epoch中要check loss epoch iter 等参数的次数
  max_num_epochs: 100 # 训练的总epoch
  eval_init_epoch: 0 # 第一次 eval的epoch
  learning_rate: 0.01 # 0.002 # 对于重新训练的模型，学习率修改 # 0.01
  optimizer: "SGD" # "SGD" "Adam" "AdamW"
  weight_decay: 0.0001   # weight decay
  momentum: 0.9          # sgd momentum
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  lr_decay: 0.95         # learning rate decay per epoch after initial cycle (from min lr)
